-- ============================================================
-- QUINIELA CONTRA - Supabase Migration Script
-- Generado desde: db_cluster-23-08-2025 backup
-- ============================================================

-- 1. TABLAS
-- ============================================================

-- tbl_users: perfiles de usuario (sincronizado desde auth.users)
CREATE TABLE IF NOT EXISTS public.tbl_users (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    name text,
    email text,
    url_image text
);

-- tbl_predictions: pronósticos de los usuarios
CREATE TABLE IF NOT EXISTS public.tbl_predictions (
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    id_user uuid DEFAULT auth.uid() NOT NULL,
    id_match bigint NOT NULL,
    score_home smallint DEFAULT '0'::smallint,
    score_visit smallint DEFAULT '0'::smallint,
    name_home text,
    name_visit text,
    image_home text,
    image_visit text,
    points smallint,
    status_match text DEFAULT 'TIMED'::text,
    result_visit smallint,
    result_home smallint
);

-- tbl_matches: partidos desde la API de football
CREATE TABLE IF NOT EXISTS public.tbl_matches (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    id_match text,
    home_team text,
    away_team text,
    score_home smallint DEFAULT '0'::smallint,
    score_away smallint DEFAULT '0'::smallint
);

-- tbl_quiniela: quinielas
CREATE TABLE IF NOT EXISTS public.tbl_quiniela (
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    score_home smallint,
    score_visit smallint,
    user_name text,
    id_match text NOT NULL,
    name_home text,
    name_visit text,
    image_home text,
    image_visit text,
    id_user uuid DEFAULT auth.uid() NOT NULL
);

-- tbl_rank: ranking
CREATE TABLE IF NOT EXISTS public.tbl_rank (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    user_name text
);

-- tbl_results: resultados
CREATE TABLE IF NOT EXISTS public.tbl_results (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    id_match bigint,
    local_score smallint DEFAULT '0'::smallint,
    visit_score smallint DEFAULT '0'::smallint,
    id_user uuid
);

-- 2. PRIMARY KEYS
-- ============================================================
ALTER TABLE ONLY public.tbl_matches
    ADD CONSTRAINT tbl_matches_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.tbl_predictions
    ADD CONSTRAINT tbl_predictions_pkey PRIMARY KEY (id_user, id_match);

ALTER TABLE ONLY public.tbl_rank
    ADD CONSTRAINT tbl_rank_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.tbl_results
    ADD CONSTRAINT tbl_results_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.tbl_users
    ADD CONSTRAINT tbl_users_pkey PRIMARY KEY (id);

-- NOTA: tbl_quiniela no tiene PK explícita en el backup

-- 3. FOREIGN KEYS
-- ============================================================
ALTER TABLE ONLY public.tbl_predictions
    ADD CONSTRAINT public_tbl_predictions_id_user_fkey
    FOREIGN KEY (id_user) REFERENCES auth.users(id)
    ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE ONLY public.tbl_results
    ADD CONSTRAINT public_tbl_results_id_user_fkey
    FOREIGN KEY (id_user) REFERENCES auth.users(id)
    ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE ONLY public.tbl_users
    ADD CONSTRAINT public_tbl_users_id_fkey
    FOREIGN KEY (id) REFERENCES auth.users(id)
    ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE ONLY public.tbl_quiniela
    ADD CONSTRAINT tbl_quiniela_id_user_fkey
    FOREIGN KEY (id_user) REFERENCES auth.users(id)
    ON UPDATE CASCADE ON DELETE CASCADE;

-- 4. FUNCTIONS
-- ============================================================

-- insert_user: crea perfil en tbl_users cuando se registra un usuario
CREATE OR REPLACE FUNCTION public.insert_user()
RETURNS trigger
LANGUAGE plpgsql SECURITY DEFINER
AS $$
BEGIN
  insert into public.tbl_users (id, name, email, url_image)
  values (
    NEW.id,
    NEW.raw_user_meta_data->>'name',
    NEW.raw_user_meta_data->>'email',
    NEW.raw_user_meta_data->>'picture'
  );
  return NEW;
END;
$$;

-- calculate_points_and_update_status: calcula puntos según el sistema de puntaje
CREATE OR REPLACE FUNCTION public.calculate_points_and_update_status()
RETURNS trigger
LANGUAGE plpgsql
AS $$
DECLARE
    v_points INT := 0;
    pronostic_real TEXT;
    pronostic_user TEXT;
BEGIN
    -- Determinar el pronostico del usuario (L, V o E)
    IF NEW.score_home > NEW.score_visit THEN
        pronostic_user := 'L';
    ELSIF NEW.score_home < NEW.score_visit THEN
        pronostic_user := 'V';
    ELSE
        pronostic_user := 'E';
    END IF;

    -- Determinar el pronóstico real (L, V o E)
    IF NEW.result_home > NEW.result_visit THEN
        pronostic_real := 'L';
    ELSIF NEW.result_home < NEW.result_visit THEN
        pronostic_real := 'V';
    ELSE
        pronostic_real := 'E';
    END IF;

    -- Verificar si acertó cantidad de goles de local
    IF NEW.score_home = NEW.result_home THEN
        v_points := 1;
    END IF;

    -- Verificar si acertó cantidad de goles de visita
    IF NEW.score_visit = NEW.result_visit THEN
        v_points := v_points + 1;
    END IF;

    -- Verificar si acertó resultado final
    IF pronostic_user = pronostic_real THEN
        v_points := v_points + 1;
    END IF;

    -- Aplicar penalidad si no acertó nada
    IF v_points = 0 THEN
        v_points := -1;
    END IF;

    -- Aplicar bono si acertó todo (3 puntos base + 1 extra = 4)
    IF v_points = 3 THEN
        v_points := v_points + 1;
    END IF;

    -- Actualizar puntos y estado del partido en tbl_predictions
    UPDATE tbl_predictions
    SET points = v_points,
        status_match = 'FINISHED'
    WHERE id_user = NEW.id_user AND id_match = NEW.id_match;

    RETURN NEW;
END;
$$;

-- get_user_points: obtiene ranking de usuarios con puntos totales
CREATE OR REPLACE FUNCTION public.get_user_points()
RETURNS TABLE(id_user uuid, name text, url_image text, total_points integer)
LANGUAGE plpgsql
AS $$
BEGIN
    RETURN QUERY
    SELECT u.id as id_user, u.name, u.url_image,
           COALESCE(CAST(SUM(p.points) AS INTEGER), 0) AS total_points
    FROM tbl_users u
    INNER JOIN tbl_predictions p ON u.id = p.id_user
    GROUP BY u.id, u.name, u.url_image
    ORDER BY total_points DESC;
END;
$$;

-- 5. TRIGGERS
-- ============================================================

-- Trigger: crear perfil automáticamente al registrarse
DROP TRIGGER IF EXISTS after_auth_users_insert ON auth.users;
CREATE TRIGGER after_auth_users_insert
    AFTER INSERT ON auth.users
    FOR EACH ROW
    EXECUTE FUNCTION public.insert_user();

-- Trigger: calcular puntos cuando se actualiza un pronóstico a FINISHED
DROP TRIGGER IF EXISTS calculate_points_trigger ON public.tbl_predictions;
CREATE TRIGGER calculate_points_trigger
    AFTER UPDATE ON public.tbl_predictions
    FOR EACH ROW
    WHEN ((OLD.status_match IS DISTINCT FROM NEW.status_match)
          AND (NEW.status_match = 'FINISHED'::text))
    EXECUTE FUNCTION public.calculate_points_and_update_status();

-- 6. ROW LEVEL SECURITY (RLS)
-- ============================================================

-- Habilitar RLS en todas las tablas
ALTER TABLE public.tbl_matches ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.tbl_predictions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.tbl_quiniela ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.tbl_rank ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.tbl_results ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.tbl_users ENABLE ROW LEVEL SECURITY;

-- Políticas para tbl_predictions
CREATE POLICY "Enable insert for authenticated users only" ON public.tbl_predictions
    FOR INSERT TO authenticated WITH CHECK (true);

CREATE POLICY "Enable read access for all users" ON public.tbl_predictions
    FOR SELECT TO authenticated, anon USING (true);

CREATE POLICY "Enable update for user authenticate" ON public.tbl_predictions
    FOR UPDATE TO anon USING ((id_user = id_user));

-- Políticas para tbl_matches
CREATE POLICY "Enable insert for authenticated users only" ON public.tbl_matches
    FOR INSERT TO authenticated WITH CHECK (true);

CREATE POLICY "Enable read access for all users" ON public.tbl_matches
    FOR SELECT TO authenticated USING (true);

CREATE POLICY "Enable update for autenticated only" ON public.tbl_matches
    FOR UPDATE TO authenticated USING ((id = id));

-- Políticas para tbl_quiniela
CREATE POLICY "Enable insert for authenticated users only" ON public.tbl_quiniela
    FOR INSERT TO authenticated WITH CHECK (true);

CREATE POLICY "Enable read access for all users" ON public.tbl_quiniela
    FOR SELECT TO authenticated, anon USING (true);

-- Políticas para tbl_rank
CREATE POLICY "Enable read access for all users" ON public.tbl_rank
    FOR SELECT TO authenticated USING (true);

-- Políticas para tbl_results
CREATE POLICY "Enable insert for authenticated users only" ON public.tbl_results
    FOR INSERT TO authenticated WITH CHECK (true);

CREATE POLICY "Enable read access for all users" ON public.tbl_results
    FOR SELECT TO authenticated USING (true);

-- Políticas para tbl_users
CREATE POLICY "Enable insert for authenticated users only" ON public.tbl_users
    FOR INSERT TO authenticated WITH CHECK (true);

CREATE POLICY "Enable read access for all users" ON public.tbl_users
    FOR SELECT TO authenticated USING (true);

-- 7. GRANTS
-- ============================================================
GRANT ALL ON TABLE public.tbl_matches TO anon;
GRANT ALL ON TABLE public.tbl_matches TO authenticated;
GRANT ALL ON TABLE public.tbl_matches TO service_role;

GRANT ALL ON TABLE public.tbl_predictions TO anon;
GRANT ALL ON TABLE public.tbl_predictions TO authenticated;
GRANT ALL ON TABLE public.tbl_predictions TO service_role;

GRANT ALL ON TABLE public.tbl_quiniela TO anon;
GRANT ALL ON TABLE public.tbl_quiniela TO authenticated;
GRANT ALL ON TABLE public.tbl_quiniela TO service_role;

GRANT ALL ON TABLE public.tbl_rank TO anon;
GRANT ALL ON TABLE public.tbl_rank TO authenticated;
GRANT ALL ON TABLE public.tbl_rank TO service_role;

GRANT ALL ON TABLE public.tbl_results TO anon;
GRANT ALL ON TABLE public.tbl_results TO authenticated;
GRANT ALL ON TABLE public.tbl_results TO service_role;

GRANT ALL ON TABLE public.tbl_users TO anon;
GRANT ALL ON TABLE public.tbl_users TO authenticated;
GRANT ALL ON TABLE public.tbl_users TO service_role;

GRANT ALL ON FUNCTION public.calculate_points_and_update_status() TO anon;
GRANT ALL ON FUNCTION public.calculate_points_and_update_status() TO authenticated;
GRANT ALL ON FUNCTION public.calculate_points_and_update_status() TO service_role;

GRANT ALL ON FUNCTION public.get_user_points() TO anon;
GRANT ALL ON FUNCTION public.get_user_points() TO authenticated;
GRANT ALL ON FUNCTION public.get_user_points() TO service_role;

GRANT ALL ON FUNCTION public.insert_user() TO anon;
GRANT ALL ON FUNCTION public.insert_user() TO authenticated;
GRANT ALL ON FUNCTION public.insert_user() TO service_role;
