import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { TansTackProvider } from "@/components";
import { ComponentAds } from "@/components/ads/ComponentAds";
import NProgressBar from "@/context/provider/NProgressBar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Quiniela-Contra",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es">
      <head>
        <meta name="ppck-ver" content="e53f623e73177d465a4d4d40810480b6" />
        <meta name="google-adsense-account" content="ca-pub-9948289874025409"></meta>
      </head>
      <body className={`${inter.className} bg-slate-900`}>
        <main className="">
          <TansTackProvider>
            <NProgressBar>

            {children}
            </NProgressBar>
            </TansTackProvider>
          <ComponentAds />
        </main>
      </body>
    </html>
  );
}
