import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { TansTackProvider } from "@/components";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Quiniela-Contra",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es">
      <body className={`${inter.className} bg-slate-900`}>
        <main className="">
          <TansTackProvider>{children}</TansTackProvider>
        </main>
      </body>
    </html>
  );
}
